  version: '3'
    
  services:
    db:
      image: nouchka/sqlite3
    glow:
      build: .
      command: python manage.py runserver 0.0.0.0:8000
      volumes:
        - .:/source-app
      ports:
        - "8000:8000"
      depends_on:
        - db